#!/usr/bin/env python3
# tarchiver.py
# Purpose: Creates a tar archive of a directory

# usage: ./tarchiver.py

#Author **Brandon Vajda**
#Date: Feb 16, 2021


import os

archiveDir = input("What directory do you want to archive? (Path): ")
archiveName = input("What would you like to name this archive? ")
compArchive = input("Do you want to compress the archive? (y|n): ")

while ((compArchive != 'y') and (compArchive != 'n')):

    compArc = input('Invalid Selection. Do you want to compress the archive? Please pick (y|n): ')
    compArchive = compArc

if compArchive == 'n':

     os.system('tar -cvf ' + archiveName + '.tar ' + archiveDir)
     exit()
else:
    compType = input('What type of compression do you want? (gzip|bzip2|xz): ')
    while((compType != 'gzip') and (compType != 'bzip2') and (compType != 'xz')):
        compressType = input('Invalid Selection. Please pick (gzip|bzip2|xz): ')
        compType = compressType

    if compType == 'gzip':
            os.system('tar -cvzf ' + archiveName + '.tar.gz ' + archiveDir)
            exit()
    elif compType == 'bzip2':
            os.system('tar -cjvf ' + archiveName + '.tar.bz2 ' + archiveDir)
            exit()
    else:
            os.system('tar -cJvf ' + archiveName + '.tar.xz ' + archiveDir)
            exit()
    
        
